// Auto-generated game module for 2001ASpaceOdysseyScript
export const META = {
  "title": "2001ASpaceOdysseyScript",
  "author": "Unknown",
  "aliases": []
};
export const WORD_COUNTS = {
  "SPACE": 11,
  "ODYSSEY": 6,
  "SCRIPT": 21,
  "IMSDB": 6,
  "THE": 246,
  "INTERNET": 1,
  "MOVIE": 48,
  "DATABASE": 1,
  "WEB": 1,
  "LARGEST": 1,
  "RESOURCE": 1,
  "SEARCH": 1,
  "ALPHABETICAL": 1,
  "GENRE": 1,
  "ACTION": 3,
  "ADVENTURE": 2,
  "ANIMATION": 1,
  "COMEDY": 1,
  "CRIME": 1,
  "DRAMA": 2,
  "FAMILY": 1,
  "FANTASY": 1,
  "FILM": 50,
  "NOIR": 1,
  "HORROR": 1,
  "MUSICAL": 1,
  "MYSTERY": 1,
  "ROMANCE": 1,
  "SCI": 2,
  "SHORT": 3,
  "THRILLER": 2,
  "WAR": 1,
  "WESTERN": 1,
  "TRANSCRIPTS": 1,
  "FUTURAMA": 1,
  "SEINFELD": 1,
  "SOUTH": 1,
  "PARK": 1,
  "STARGATE": 2,
  "LOST": 2,
  "SPONSOR": 1,
  "INTERNATIONAL": 1,
  "FRENCH": 1,
  "SCRIPTS": 2,
  "LATEST": 1,
  "COMMENTS": 2,
  "PREDATOR": 1,
  "MASTER": 2,
  "AND": 116,
  "COMMANDER": 1,
  "WHITE": 2,
  "CHRISTMAS": 1,
  "FANTASTIC": 1,
  "BEASTS": 1,
  "CRIMES": 1,
  "GRINDELWALD": 1,
  "LEGEND": 1,
  "OPINION": 6,
  "NONE": 2,
  "AVAILABLE": 2,
  "RATING": 5,
  "NOT": 27,
  "AVERAGE": 3,
  "USER": 2,
  "OUT": 54,
  "WRITERS": 2,
  "STANLEY": 5,
  "KUBRICK": 24,
  "ARHUR": 1,
  "CLARKE": 7,
  "GENRES": 1,
  "DATE": 2,
  "FEBRUARY": 1,
  "READ": 5,
  "FOR": 37,
  "KENNETH": 4,
  "WILL": 8,
  "GREAT": 12,
  "WRITER": 1,
  "COULD": 5,
  "IDENTIFY": 1,
  "WHICH": 8,
  "VERSION": 6,
  "THIS": 63,
  "SCREENPLAY": 8,
  "BASED": 5,
  "RENTAL": 1,
  "COPY": 1,
  "THAT": 84,
  "WATCHED": 4,
  "ACTUALLY": 2,
  "DOWNLOADED": 1,
  "DIVX": 1,
  "HAL": 5,
  "SAYS": 2,
  "DIFFERENT": 6,
  "THINGS": 2,
  "BEFORE": 3,
  "SHUT": 1,
  "OFF": 5,
  "NAMELY": 2,
  "DOES": 5,
  "REPEAT": 1,
  "MUCH": 13,
  "PERSONAL": 1,
  "INFORMATION": 4,
  "RECITE": 1,
  "PERHAPS": 3,
  "ORIGINAL": 3,
  "CLARIFICATION": 1,
  "APPRECIATED": 1,
  "LIMEY": 12,
  "LIKE": 29,
  "MANY": 4,
  "WORKS": 2,
  "ART": 10,
  "REPRESENT": 1,
  "TRIUMPH": 1,
  "STYLE": 2,
  "OVER": 6,
  "SUBSTANCE": 2,
  "VIRTUALLY": 2,
  "BLOODY": 2,
  "UNWATCHABLE": 3,
  "BUT": 48,
  "NONETHELESS": 2,
  "MUST": 3,
  "SEE": 8,
  "HAUNTED": 1,
  "WAYS": 1,
  "FIRST": 6,
  "TIME": 16,
  "SAW": 3,
  "SCENE": 5,
  "WHERE": 4,
  "SHUTTLES": 1,
  "SPIN": 1,
  "DOCKING": 1,
  "SET": 1,
  "STRAUSS": 2,
  "BOTH": 3,
  "MESMERISING": 1,
  "ICONIC": 1,
  "TIMES": 6,
  "INDEED": 2,
  "CAN": 24,
  "LITTLE": 4,
  "COLD": 5,
  "CLINICAL": 3,
  "CLOSEST": 1,
  "PORTRAYAL": 2,
  "LIFE": 4,
  "WITHOUT": 3,
  "DOUBT": 3,
  "MASTERPIECE": 5,
  "CINEMATOGRAPHY": 1,
  "THOUGH": 4,
  "ADMIT": 3,
  "ARDUOUS": 2,
  "CHORE": 1,
  "KEVIN": 4,
  "SETTLE": 1,
  "DOWN": 6,
  "YOU": 65,
  "CONTROL": 1,
  "WITH": 19,
  "VERBIAGE": 1,
  "HOW": 5,
  "ABOUT": 18,
  "EXCELLENT": 4,
  "GIVE": 5,
  "BIG": 4,
  "THUMBS": 1,
  "SAY": 15,
  "BECAUSE": 15,
  "WHEN": 15,
  "WAS": 32,
  "AMAZED": 2,
  "INCREDIBLE": 1,
  "AAW": 1,
  "SHUCKS": 1,
  "NINE": 5,
  "TEN": 5,
  "WASN": 3,
  "ENOUGH": 3,
  "HEAVEN": 1,
  "FORBID": 1,
  "SHOULD": 4,
  "HAVE": 32,
  "MIXED": 1,
  "SAID": 9,
  "ISN": 4,
  "EASY": 4,
  "VIEWING": 2,
  "STAND": 1,
  "SURE": 4,
  "WHY": 5,
  "GOT": 6,
  "SUCH": 4,
  "BEE": 1,
  "YOUR": 10,
  "BONNET": 1,
  "TRY": 2,
  "ANOTHER": 2,
  "BARELY": 2,
  "WATCHABLE": 3,
  "WORK": 9,
  "GENIUS": 3,
  "BLUE": 2,
  "DEREK": 1,
  "JARMAN": 2,
  "THEN": 7,
  "TALK": 1,
  "MOVIES": 10,
  "BEING": 4,
  "FULL": 4,
  "STOP": 3,
  "AGAINST": 2,
  "JUST": 12,
  "SCREEN": 3,
  "HOUR": 1,
  "MINUTE": 1,
  "LONG": 3,
  "FEATURES": 1,
  "COLLAGE": 1,
  "SNIPPETS": 1,
  "SOUND": 3,
  "MEDITATIONS": 1,
  "HIS": 5,
  "FAST": 1,
  "APPROACHING": 1,
  "DEATH": 2,
  "ACHINGLY": 1,
  "POIGNANT": 1,
  "MOVING": 1,
  "ALSO": 5,
  "COMPLETELY": 2,
  "NUMBING": 2,
  "WOULD": 17,
  "DEFY": 1,
  "WATCH": 10,
  "SECOND": 1,
  "REALLY": 3,
  "WHAT": 16,
  "POINT": 2,
  "RATHER": 2,
  "CONDESCENDING": 2,
  "SAM": 1,
  "SON": 1,
  "WHO": 16,
  "THREE": 4,
  "HALF": 2,
  "HAS": 16,
  "FALLEN": 1,
  "LOVE": 3,
  "WANTS": 2,
  "EVERYDAY": 1,
  "SEEMS": 3,
  "GET": 9,
  "LOT": 4,
  "NUANCES": 1,
  "PEOPLE": 19,
  "MISS": 1,
  "BACK": 6,
  "BEGINNING": 2,
  "SHOUTED": 1,
  "THROUGH": 3,
  "STAR": 5,
  "CHILD": 4,
  "EMERGED": 1,
  "FIND": 7,
  "HARD": 2,
  "IMAGINE": 1,
  "SOMEBODY": 1,
  "CALLING": 1,
  "ONE": 15,
  "MOST": 11,
  "BEAUTIFUL": 5,
  "FILMS": 8,
  "EVER": 9,
  "MADE": 4,
  "PHOTOGRAPHER": 1,
  "CLEARLY": 2,
  "SHOWS": 3,
  "THERE": 12,
  "REAL": 2,
  "BEAUTY": 2,
  "ALMOST": 9,
  "EVERY": 6,
  "FRAME": 2,
  "SENSATION": 1,
  "SLOW": 8,
  "PENSIVE": 1,
  "ITS": 11,
  "OWN": 11,
  "THOUGHTS": 1,
  "MEANS": 1,
  "WHATEVER": 1,
  "WANT": 7,
  "MEAN": 4,
  "OTHER": 7,
  "WORDS": 2,
  "MAY": 1,
  "NOTHING": 1,
  "CHARACTERS": 2,
  "ARE": 20,
  "BLANK": 2,
  "ROBOTIC": 1,
  "PERFECT": 4,
  "ARTISTIC": 1,
  "REPRESENTATION": 1,
  "UNINVOLVING": 1,
  "MOVIEGOER": 1,
  "EXPECTS": 1,
  "MIDDLE": 1,
  "END": 8,
  "STUNNING": 2,
  "SOMEWHAT": 2,
  "LESS": 4,
  "ANONYMOUS": 3,
  "TOTALLY": 2,
  "OVERRATED": 1,
  "MAKES": 4,
  "THINK": 16,
  "SOMETHING": 11,
  "GOING": 5,
  "HAPPEN": 2,
  "ALL": 20,
  "CONFUSE": 2,
  "HELL": 2,
  "GUY": 2,
  "THING": 6,
  "HATE": 3,
  "THEY": 22,
  "ADORE": 1,
  "CLOCKWORK": 3,
  "ORANGE": 2,
  "SIMPLY": 5,
  "BORING": 5,
  "NOW": 6,
  "STUPID": 3,
  "INTERESTED": 1,
  "OUR": 4,
  "MEANING": 6,
  "PLANET": 1,
  "AREN": 4,
  "OPEN": 2,
  "MINDED": 3,
  "SUBJECT": 3,
  "EARTH": 3,
  "ATTACKS": 2,
  "EMOTIONS": 2,
  "USED": 4,
  "FEELING": 3,
  "WHEREAS": 2,
  "THEME": 2,
  "STILL": 6,
  "ONLY": 5,
  "MINUTES": 3,
  "DIALOGUE": 1,
  "RUNTIME": 1,
  "HOURS": 2,
  "BORED": 3,
  "VISUAL": 3,
  "TRIP": 1,
  "UNDERSTAND": 5,
  "SHOT": 1,
  "EXISTENCE": 1,
  "EVOLUTION": 2,
  "HUMAN": 4,
  "BEINGS": 2,
  "DON": 12,
  "WAIT": 1,
  "EXPLANATION": 2,
  "EVERYTHING": 2,
  "MAKE": 6,
  "STORY": 5,
  "HEAD": 2,
  "GAVE": 4,
  "FAR": 5,
  "MEMORY": 1,
  "WERE": 9,
  "SPERM": 1,
  "CHILLIN": 1,
  "DADS": 1,
  "TESTIS": 1,
  "SAME": 7,
  "ENDING": 4,
  "VERY": 13,
  "SMALL": 2,
  "BODY": 2,
  "REPRESENTED": 1,
  "HUGE": 3,
  "UNIVERSE": 3,
  "BORN": 1,
  "HIM": 4,
  "RIGHT": 4,
  "ESCAPE": 1,
  "ESCAPED": 1,
  "MOTHERS": 1,
  "ENTER": 1,
  "WORLD": 6,
  "NEVER": 4,
  "KNOW": 8,
  "EVAN": 2,
  "ENTERTAINS": 1,
  "PROBLEM": 1,
  "EVEN": 12,
  "PAST": 2,
  "NOAM": 2,
  "INSANE": 1,
  "THOROUGHLY": 2,
  "AGREE": 5,
  "AIN": 1,
  "ENJOY": 4,
  "BARRY": 2,
  "LYNDON": 2,
  "MAYBE": 4,
  "METAL": 2,
  "JACKET": 2,
  "TRADITIONAL": 1,
  "KIND": 5,
  "VIDEOART": 1,
  "INSPIRED": 1,
  "COMBINATION": 1,
  "IMAGES": 1,
  "MUSIC": 5,
  "EXCEPT": 1,
  "LIGETI": 2,
  "TIRESOME": 1,
  "INTO": 7,
  "PHILOSOPHY": 2,
  "HEAVY": 1,
  "IMPORTANT": 1,
  "CONSIDER": 1,
  "VIDEO": 1,
  "SPOKE": 1,
  "ZARATHUSTRA": 1,
  "NICK": 2,
  "SPLENDID": 1,
  "BIT": 1,
  "PLOD": 1,
  "PIECE": 4,
  "ENTERTAINMENT": 1,
  "FREAKOUT": 1,
  "APPEARS": 1,
  "ROOM": 2,
  "EFFECT": 1,
  "FILTER": 1,
  "BOX": 2,
  "LET": 4,
  "FACE": 1,
  "QUITE": 4,
  "LIMITED": 1,
  "WATCHING": 6,
  "SAVER": 1,
  "CUT": 4,
  "WHOLE": 3,
  "MISSING": 1,
  "CENTRAL": 1,
  "THEMES": 1,
  "SUPPOSED": 1,
  "WHILE": 4,
  "BREAK": 1,
  "NECK": 1,
  "ROLLERCOASTER": 1,
  "SOME": 9,
  "MORE": 10,
  "RECENT": 2,
  "FLICKS": 2,
  "LANDMARK": 2,
  "EARNED": 1,
  "PLACE": 2,
  "TOP": 2,
  "ARRAY": 1,
  "CURTIN": 1,
  "FLAWED": 1,
  "FASCINATING": 4,
  "ANYTHING": 1,
  "FINALLY": 1,
  "CAME": 2,
  "OBVIOUSLY": 3,
  "EARLY": 2,
  "DRAFT": 6,
  "WELL": 1,
  "SLIGHTLY": 1,
  "ARTHUR": 1,
  "WROTE": 1,
  "WHILST": 1,
  "SIMULTANEOUSLY": 2,
  "WRITING": 1,
  "NOVELLISATION": 1,
  "PRETTY": 4,
  "TELL": 5,
  "FROM": 9,
  "AMOUNTS": 1,
  "NARRATION": 3,
  "JERRY": 1,
  "VEGAS": 1,
  "SEEM": 2,
  "EDUCATED": 1,
  "INTELLIGENT": 1,
  "ARTICULATE": 1,
  "COME": 3,
  "ASK": 1,
  "QUESTION": 2,
  "SAD": 2,
  "LIVE": 2,
  "EXPLODE": 1,
  "MOVE": 2,
  "QUICKLY": 1,
  "THAN": 9,
  "ANY": 7,
  "EACH": 4,
  "LOOKING": 1,
  "PAINTING": 3,
  "PHOTOGRAPH": 1,
  "FAVORITE": 1,
  "FACT": 4,
  "BETTER": 3,
  "DIRECTORS": 4,
  "TODAY": 5,
  "PUT": 2,
  "THOUGHT": 7,
  "THEIR": 3,
  "DID": 2,
  "INSTEAD": 2,
  "BRAVE": 1,
  "NEW": 2,
  "TYPE": 1,
  "ENCOURAGE": 1,
  "SIT": 3,
  "COLORS": 1,
  "DIZZY": 1,
  "PRETENTIOUS": 1,
  "SNOB": 1,
  "NIGHT": 2,
  "LIVING": 1,
  "DEAD": 1,
  "SIMILAR": 1,
  "CONSIDERED": 1,
  "GREATEST": 5,
  "REASON": 3,
  "HIGH": 2,
  "DAVID": 3,
  "BEYOND": 2,
  "COMPARE": 2,
  "PURE": 1,
  "ELEMENT": 1,
  "EXACT": 1,
  "TIMING": 1,
  "DURATION": 1,
  "PACE": 1,
  "SILENCE": 2,
  "INSTRUMENT": 3,
  "VOID": 1,
  "AMUSING": 1,
  "THOSE": 5,
  "FEEBLE": 2,
  "MINDS": 1,
  "COURAGE": 1,
  "TOO": 4,
  "CONFESS": 1,
  "WAY": 7,
  "THESE": 6,
  "ADMITTING": 1,
  "LOW": 2,
  "INTELLIGENCE": 1,
  "CULTURE": 1,
  "GETTING": 2,
  "CHAT": 1,
  "BOARD": 2,
  "TRYING": 3,
  "DISMISS": 1,
  "CLASSIC": 1,
  "LACK": 1,
  "WORD": 1,
  "RETARDED": 1,
  "COMES": 3,
  "RENT": 1,
  "AMERICAN": 1,
  "PIE": 1,
  "MAN": 3,
  "QUIT": 1,
  "CRITIC": 2,
  "COURSE": 3,
  "HERE": 5,
  "TYPING": 1,
  "DALLAS": 1,
  "NEED": 2,
  "ENTERTAINED": 1,
  "MINDLESS": 2,
  "MIDLAND": 1,
  "STUDENT": 1,
  "SEEN": 9,
  "YET": 5,
  "AWESOME": 1,
  "GUYS": 1,
  "FAITH": 1,
  "HOPE": 1,
  "GOOD": 3,
  "LAUNCHED": 1,
  "TIRADE": 1,
  "DISLIKING": 1,
  "MISSED": 1,
  "EVERYONE": 2,
  "EXCEPTION": 1,
  "SPOKEN": 1,
  "ADMIRATION": 2,
  "CINEMATIC": 1,
  "TEMPERED": 1,
  "FOUND": 2,
  "DOZEN": 1,
  "ORDER": 1,
  "FATHOM": 1,
  "DEPTHS": 1,
  "ANYONE": 1,
  "PRETENDS": 1,
  "ALWAYS": 1,
  "KIDDING": 1,
  "THEMSELVES": 1,
  "ADMITTED": 1,
  "ABLE": 1,
  "RECOGNISE": 1,
  "FINE": 2,
  "SHOWN": 1,
  "CANDID": 1,
  "SELF": 2,
  "EFFACING": 1,
  "ALLL": 1,
  "AFFECTED": 1,
  "DEEPLY": 1,
  "EXPERIENCE": 1,
  "PERSEVERANCE": 1,
  "PLODDING": 1,
  "RELEASE": 2,
  "YORK": 1,
  "DESCRIBED": 1,
  "SOMEWHERE": 2,
  "BETWEEN": 3,
  "HYPNOTIC": 1,
  "IMMENSELY": 2,
  "COULDN": 3,
  "PREFER": 1,
  "TOWED": 1,
  "LINE": 2,
  "VOICED": 1,
  "DRIED": 1,
  "OPINIONS": 1,
  "FEAR": 1,
  "COMPLICATED": 1,
  "THANKS": 2,
  "BACKING": 1,
  "SHALL": 1,
  "NAIL": 1,
  "COLOURS": 1,
  "MAST": 1,
  "ISSUE": 1,
  "AWARDING": 1,
  "SQUID": 1,
  "THIRTEEN": 1,
  "YEARS": 4,
  "AGE": 1,
  "ATTENTION": 2,
  "SHORTAGE": 1,
  "CLOSE": 2,
  "ENJOYED": 1,
  "MAINLY": 1,
  "VIEWERS": 1,
  "GIVING": 1,
  "CRITICAL": 1,
  "REVIEWS": 2,
  "EXPECTATIONS": 1,
  "EXPECT": 1,
  "SORT": 1,
  "THRILL": 1,
  "RIDE": 1,
  "SUPPOSE": 1,
  "LOOK": 4,
  "OBSERVED": 1,
  "STUDIED": 1,
  "REALIZE": 3,
  "TALKING": 1,
  "FEW": 3,
  "DOUBTFUL": 1,
  "DIFFERENCE": 2,
  "MIND": 4,
  "ODD": 1,
  "RARELY": 1,
  "TALKED": 1,
  "REVIEW": 1,
  "HELPED": 1,
  "INTERESTING": 2,
  "PROPS": 1,
  "MANAGED": 1,
  "CONVERT": 1,
  "ALTHOUGH": 2,
  "PROBABLY": 3,
  "HAD": 8,
  "IDEA": 3,
  "ALREADY": 1,
  "BOOK": 19,
  "BESIDES": 2,
  "CONVERSATION": 1,
  "ODDLY": 1,
  "WRITTEN": 3,
  "ENTERTAINING": 1,
  "LASTMAN": 1,
  "SOMETIMES": 3,
  "WATCHES": 1,
  "SPOILT": 1,
  "CGI": 2,
  "EFFECTS": 2,
  "GOES": 1,
  "WISE": 1,
  "STILLS": 1,
  "STANDS": 1,
  "ACHIEVMENT": 1,
  "COMPARED": 1,
  "ERA": 1,
  "JAMIE": 2,
  "WORTH": 2,
  "HAND": 2,
  "DATED": 1,
  "JULY": 1,
  "LENGTHY": 1,
  "BOWMAN": 3,
  "NON": 1,
  "DESCRIPT": 1,
  "HOTEL": 1,
  "PULLS": 1,
  "DRAPE": 1,
  "SEES": 1,
  "INFINITY": 1,
  "ETC": 2,
  "KEITH": 1,
  "AGAIN": 3,
  "CONFUSED": 1,
  "MAGNITUDE": 1,
  "FINAL": 4,
  "TREASURE": 1,
  "THUS": 1,
  "POST": 1,
  "VERSUS": 2,
  "PRE": 1,
  "VALUABLE": 1,
  "KIERAN": 1,
  "DIES": 1,
  "SAYING": 1,
  "DAVE": 4,
  "AFRAID": 2,
  "FEEL": 2,
  "SINGS": 1,
  "SONG": 1,
  "MATT": 2,
  "CONFUSING": 1,
  "INCREDIBLY": 2,
  "STRAIGHTFORWARD": 1,
  "CLIFF": 2,
  "NOTES": 2,
  "EXPLAINS": 2,
  "EXACTLY": 2,
  "BLACK": 1,
  "OBELISKS": 1,
  "INTENDED": 1,
  "HOWEVER": 3,
  "ALFIE": 1,
  "WORKED": 2,
  "ONCE": 1,
  "ARGUMENT": 1,
  "BEEN": 5,
  "TITLED": 1,
  "VICE": 1,
  "VERSA": 1,
  "TEND": 1,
  "SEPARATE": 1,
  "THEM": 2,
  "LARGE": 1,
  "ENTITY": 1,
  "WEIRD": 1,
  "AMALGAMATION": 1,
  "REALITY": 1,
  "SEED": 1,
  "SPROUTED": 1,
  "CONTAINING": 1,
  "QUIET": 1,
  "DOCUMENT": 1,
  "HAMMER": 1,
  "HOME": 2,
  "EXAMPLE": 2,
  "CLAVIUS": 1,
  "REPEATED": 1,
  "WEREN": 1,
  "REPETITION": 1,
  "LIKED": 1,
  "SPECIFICALLY": 1,
  "LEFT": 3,
  "LATER": 2,
  "DECISION": 1,
  "PRACTICALLY": 1,
  "HOSTILE": 1,
  "TOWARDS": 2,
  "VIEWER": 1,
  "GIVEN": 2,
  "DIRECTLY": 1,
  "PARTS": 3,
  "PLOT": 2,
  "PRESENTATION": 1,
  "PERPLEXING": 1,
  "EITHER": 1,
  "AUTOMATIC": 1,
  "RESPONSE": 2,
  "PLEA": 1,
  "SCIENCE": 2,
  "FICTION": 2,
  "NEARLY": 1,
  "FLAWLESS": 1,
  "WISH": 1,
  "DIDN": 5,
  "MOVES": 1,
  "FASTER": 1,
  "FITS": 1,
  "TOGETHER": 2,
  "CLEANER": 1,
  "NONSENSICAL": 1,
  "PULLED": 1,
  "LACKLUSTER": 1,
  "CRITICS": 1,
  "ABSOLUTELY": 6,
  "NARRATOR": 1,
  "ENTIRELY": 1,
  "EXPOSITION": 1,
  "POPULAR": 1,
  "UPON": 1,
  "TERM": 2,
  "CARRIES": 1,
  "WEIGHT": 1,
  "DOESN": 6,
  "CULTURAL": 1,
  "ICON": 1,
  "RRRRCOMPOSER": 1,
  "CERTAINLY": 1,
  "CLOSER": 1,
  "ACHIEVING": 1,
  "LEVEL": 1,
  "SYMPHONY": 3,
  "BALLET": 1,
  "EXPERIENCED": 1,
  "MERELY": 2,
  "ELOQUENT": 1,
  "USE": 1,
  "CLASSICAL": 2,
  "THROUGHOUT": 2,
  "UNFOLDS": 2,
  "SEVERAL": 1,
  "DISTINCT": 1,
  "SUPERFICIALLY": 1,
  "UNRELATED": 1,
  "UNDENIABLY": 1,
  "MOVEMENTS": 1,
  "EXISTS": 1,
  "OFFICE": 1,
  "RETURNS": 1,
  "SAKE": 1,
  "REQUIRES": 1,
  "AUDIENCES": 2,
  "UNLIKE": 2,
  "HOLLYWOOD": 1,
  "AIMED": 1,
  "POPCORN": 1,
  "HAPPENS": 1,
  "SPELLED": 1,
  "DULLARD": 1,
  "ILL": 1,
  "ADVISED": 1,
  "UTTERLY": 1,
  "MEDIOCRE": 1,
  "SEQUEL": 1,
  "MENTIONING": 1,
  "THINKING": 1,
  "PLEASE": 1,
  "UNCONVENTIONAL": 1,
  "MILLIONS": 1,
  "CHARACTER": 4,
  "MAIN": 2,
  "MANKIND": 2,
  "HIMSELF": 1,
  "PROFOUND": 1,
  "CLIMACTIC": 1,
  "CONCLUSION": 1,
  "ORGASMIC": 1,
  "INTENSITY": 1,
  "CONSIDERABLY": 1,
  "MESSY": 1,
  "YES": 1,
  "MAGNIFICENTLY": 1,
  "DIRECTED": 1,
  "FAIL": 1,
  "SAFE": 1,
  "BUTTON": 1,
  "MIXTURE": 1,
  "ASTONISHING": 1,
  "VISUALS": 1,
  "COMBINED": 1,
  "DISTANT": 1,
  "ACTING": 1,
  "BAD": 3,
  "PERFECTLY": 1,
  "CRAFTED": 1,
  "DESCENT": 1,
  "NEXT": 3,
  "STAGE": 2,
  "PAY": 1,
  "TELLS": 1,
  "BEST": 3,
  "LEVELS": 1,
  "MIGHT": 1,
  "SHINING": 3,
  "PLAYS": 1,
  "PRESENCE": 1,
  "MONOLITH": 4,
  "POWERFUL": 1,
  "EERIE": 1,
  "HORRIFIC": 1,
  "KEPT": 1,
  "WORSE": 1,
  "NIGHTMARES": 1,
  "ENTIRETY": 1,
  "ESPECIALLY": 2,
  "CAPTAIN": 1,
  "COHEN": 1,
  "YEAR": 1,
  "OLD": 3,
  "REVISIT": 1,
  "OFTEN": 1,
  "RENEWED": 1,
  "DEEPER": 1,
  "HAUNTING": 2,
  "HOPEFUL": 1,
  "ADDED": 1,
  "FOLLOWING": 1,
  "TRAIN": 1,
  "UNDERSTANDING": 1,
  "HOMER": 1,
  "HERO": 1,
  "CHANGED": 1,
  "HAPPENED": 1,
  "DEATHS": 1,
  "FRIENDS": 1,
  "BETRAYAL": 1,
  "REJECTION": 1,
  "BATTLE": 1,
  "SIGHT": 1,
  "FOREIGN": 1,
  "DARE": 1,
  "ALIEN": 1,
  "PICTURE": 1,
  "KID": 1,
  "BEACH": 1,
  "READING": 2,
  "REMEMBER": 1,
  "AFTER": 3,
  "SEEING": 1,
  "LECTURES": 1,
  "MONOLITHS": 1,
  "OBELISK": 1,
  "AROUND": 1,
  "SELECTION": 1,
  "TEACHING": 1,
  "OCCURS": 1,
  "FULLY": 1,
  "BUILDERS": 1,
  "DESIGNERS": 1,
  "RECALL": 1,
  "LAST": 2,
  "PAGE": 1,
  "STATES": 2,
  "BECOME": 1,
  "ONES": 1,
  "CREATED": 1,
  "SENTINEL": 1,
  "DISCUSSING": 1,
  "MAGNIFICENCE": 1,
  "HEARTFELT": 1,
  "TORICK": 1,
  "INTRIGUE": 1,
  "MASTERFUL": 1,
  "DIRECTOR": 1,
  "INDULGENT": 1,
  "STRUGGLED": 1,
  "INTENTION": 1,
  "ICE": 1,
  "HUMANITY": 2,
  "TURNED": 1,
  "ITSELF": 2,
  "TECHNOLOGY": 3,
  "FEELINGS": 1,
  "APPARENT": 1,
  "DULL": 3,
  "TAKING": 1,
  "MISSION": 2,
  "EXCITED": 1,
  "OWING": 1,
  "FOLLY": 1,
  "STARVING": 1,
  "DYING": 1,
  "CATCH": 2,
  "FOOD": 2,
  "PROTECT": 1,
  "OURSELVES": 1,
  "SAVED": 2,
  "MONOLITHIC": 1,
  "INTERVENTION": 1,
  "TOOK": 1,
  "GIANT": 1,
  "EVOLUTIONARY": 1,
  "STEP": 1,
  "FORWARD": 1,
  "LUCKY": 1,
  "HUMANS": 2,
  "REFLECTIONS": 1,
  "CANDIDATE": 1,
  "CITIZEN": 1,
  "KANE": 1,
  "INTERPRETATION": 1,
  "TWO": 3,
  "AUTHORS": 1,
  "TRUE": 1,
  "COSMOLOGY": 1,
  "LATE": 2,
  "SIXTIES": 1,
  "PLAYBOY": 1,
  "INTERVIEW": 1,
  "EXTRATERRESTRIAL": 1,
  "THESIS": 1,
  "WANGARI": 1,
  "KIRAGU": 1,
  "KENYA": 2,
  "NOBODY": 2,
  "KNOWS": 1,
  "STUFF": 3,
  "SOCIAL": 1,
  "OUTCAST": 1,
  "STAYING": 1,
  "TCM": 1,
  "BRILLIANT": 3,
  "EDUCATION": 1,
  "DREAM": 1,
  "CONFIDENCE": 1,
  "GUTS": 1,
  "TALENT": 1,
  "PULL": 1,
  "GEORGE": 1,
  "LUCAS": 1,
  "DONE": 1,
  "TAKEN": 1,
  "ANTI": 1,
  "COMPUTERS": 1,
  "FIGHT": 1,
  "STARTED": 2,
  "SLOWLY": 1,
  "TURNING": 1,
  "POOLE": 1,
  "ANYWAYS": 1,
  "REY": 1,
  "OKAY": 3,
  "SOMEONE": 4,
  "DEFINITIVE": 1,
  "ANSWER": 1,
  "LOVED": 1,
  "TRANSFORMERS": 1,
  "WORST": 1,
  "CORRECT": 1,
  "PROVOKING": 2,
  "IDEAS": 1,
  "ALTOGETHER": 1,
  "FRESH": 1,
  "AHEAD": 1,
  "HORSES": 1,
  "LIKING": 1,
  "SMARTER": 1,
  "PART": 2,
  "APE": 2,
  "STOOD": 1,
  "BONE": 2,
  "CLUB": 1,
  "KNEW": 3,
  "POWER": 2,
  "FLOATED": 1,
  "ORBIT": 1,
  "ABOVE": 1,
  "CAPACITY": 1,
  "ABILITY": 1,
  "DEBATE": 1,
  "TOSSES": 1,
  "AIR": 1,
  "BECOMES": 1,
  "SATELLITE": 1,
  "ORBITING": 2,
  "WEAPONS": 1,
  "PLATFORM": 1,
  "COMMENTED": 1,
  "SECONDS": 1,
  "MODERN": 1,
  "FLOYD": 1,
  "ASLEEP": 1,
  "PAN": 1,
  "SHUTTLE": 2,
  "PEN": 2,
  "FLOATING": 1,
  "CABIN": 1,
  "MIGHTIER": 1,
  "SWORD": 1,
  "STANLY": 1,
  "OPTIMIST": 1,
  "TOOLS": 1,
  "MOTIFS": 1,
  "RECUR": 1,
  "SUCK": 1,
  "THUMB": 1,
  "SUBTLE": 1,
  "RESPONDING": 1,
  "COMMENT": 3,
  "NOTORIOUS": 1,
  "REWRITING": 1,
  "DURING": 2,
  "FILMING": 1,
  "SCENES": 1,
  "REWRITTEN": 1,
  "DAILY": 1,
  "BASIS": 1,
  "INCLUDING": 1,
  "SHOW": 1,
  "DIFFERENCES": 1,
  "MENTIONED": 1,
  "NONEXISTENT": 1,
  "DARIUS": 2,
  "CONTRARY": 1,
  "BELIEVE": 1,
  "FUN": 2,
  "ADMITTEDLY": 1,
  "UNLESS": 1,
  "HAVEN": 1,
  "CAUSED": 1,
  "SUDDENLY": 1,
  "EVOLVE": 1,
  "TAKES": 2,
  "DENSE": 1,
  "AUDIENCE": 1,
  "FIGURE": 1,
  "GIDDY": 1,
  "ENJOYMENT": 1,
  "DRAW": 1,
  "INTENSE": 1,
  "SUSPENSE": 1,
  "HITCHCOCK": 1,
  "SCORCESE": 1,
  "GRATEFUL": 1,
  "GENIUSES": 1,
  "ARGUING": 1,
  "IMPROVE": 1,
  "PROVIDED": 1,
  "SITE": 1,
  "BIZARRE": 1,
  "ANDREW": 1,
  "HOPKINSON": 1,
  "EXTREMELY": 2,
  "INTELECTUALS": 1,
  "WRITE": 1,
  "EMOTIONALLY": 1,
  "GEE": 1,
  "WHIZ": 1,
  "SPOILED": 1,
  "SHOTS": 1,
  "REALISTIC": 1,
  "OUTER": 1,
  "WARS": 1,
  "SPENDING": 1,
  "MANEUVERS": 1,
  "TOTAL": 1,
  "SEQUENCE": 1,
  "HOLDS": 1,
  "REVISIONS": 1,
  "NOTABLY": 1,
  "REMOVAL": 1,
  "CHOICE": 1,
  "FAIRLY": 1,
  "DEFINITELY": 1,
  "WORDLY": 1,
  "COLLAGES": 1,
  "ADD": 1,
  "NAME": 1,
  "MAIL": 1,
  "CHOOSE": 1,
  "AWFUL": 1,
  "INDEX": 1,
  "SUBMIT": 1,
  "LINK": 1,
  "DISCLAIMER": 1,
  "PRIVACY": 1,
  "POLICY": 1,
  "CONTACT": 1
};
export const COMMON_TOP20 = [
  [
    "OUT",
    54
  ],
  [
    "FILM",
    50
  ],
  [
    "MOVIE",
    48
  ],
  [
    "HAVE",
    32
  ],
  [
    "LIKE",
    29
  ],
  [
    "CAN",
    24
  ],
  [
    "KUBRICK",
    24
  ],
  [
    "SCRIPT",
    21
  ],
  [
    "ALL",
    20
  ],
  [
    "BOOK",
    19
  ],
  [
    "PEOPLE",
    19
  ],
  [
    "ABOUT",
    18
  ],
  [
    "WOULD",
    17
  ],
  [
    "HAS",
    16
  ],
  [
    "THINK",
    16
  ],
  [
    "TIME",
    16
  ],
  [
    "BECAUSE",
    15
  ],
  [
    "ONE",
    15
  ],
  [
    "SAY",
    15
  ],
  [
    "MUCH",
    13
  ]
];
export const UNCOMMON_TOP20 = [
  [
    "ACTUALLY",
    2
  ],
  [
    "ADMIRATION",
    2
  ],
  [
    "ADVENTURE",
    2
  ],
  [
    "AFRAID",
    2
  ],
  [
    "AGAINST",
    2
  ],
  [
    "ALTHOUGH",
    2
  ],
  [
    "AMAZED",
    2
  ],
  [
    "ANOTHER",
    2
  ],
  [
    "APE",
    2
  ],
  [
    "ARDUOUS",
    2
  ],
  [
    "ATTACKS",
    2
  ],
  [
    "ATTENTION",
    2
  ],
  [
    "AUDIENCES",
    2
  ],
  [
    "AVAILABLE",
    2
  ],
  [
    "BARELY",
    2
  ],
  [
    "BARRY",
    2
  ],
  [
    "BEAUTY",
    2
  ],
  [
    "BEGINNING",
    2
  ],
  [
    "BEINGS",
    2
  ],
  [
    "BESIDES",
    2
  ]
];

// Game-ready object
export const BOOK_FOR_GAME = {
  ...META,
  commonTop: COMMON_TOP20,
  uncommonTop: UNCOMMON_TOP20
};

export default BOOK_FOR_GAME;
