// Auto-generated game module for Ghostbusters
export const META = {
  "title": "Ghostbusters",
  "author": "Unknown",
  "aliases": []
};
export const WORD_COUNTS = {
  "POULTRYGEIST": 1,
  "DUANE": 1,
  "CAPIZZI": 1,
  "AND": 169,
  "STEVEN": 1,
  "ROBERTS": 1,
  "LAST": 2,
  "REVISED": 1,
  "MAY": 1,
  "EXT": 12,
  "FARMHOUSE": 8,
  "OUTSIDE": 2,
  "NEW": 3,
  "YORK": 1,
  "CITY": 4,
  "NIGHT": 18,
  "THE": 283,
  "ROOF": 1,
  "CHICKEN": 49,
  "SHAPED": 1,
  "WEATHERVANE": 1,
  "STANDS": 4,
  "SILHOUETTED": 2,
  "AGAINST": 1,
  "FULL": 12,
  "BLOOD": 4,
  "RED": 14,
  "MOON": 9,
  "WIND": 5,
  "HOWLS": 4,
  "VANE": 1,
  "SWIVELS": 1,
  "WITH": 47,
  "EERIE": 2,
  "SQUEAK": 1,
  "THEN": 25,
  "WEIRD": 2,
  "ANIMAL": 1,
  "CRY": 1,
  "HEARD": 3,
  "CROSS": 2,
  "BETWEEN": 1,
  "CROWING": 1,
  "WOLF": 1,
  "HOWLING": 1,
  "FENCED": 2,
  "DIRT": 3,
  "AREA": 1,
  "NUMEROUS": 1,
  "CHICKENS": 7,
  "MILLING": 1,
  "AROUND": 18,
  "CLUCKING": 4,
  "THEY": 30,
  "PECK": 1,
  "GROUND": 3,
  "ANOTHER": 4,
  "HOWL": 10,
  "NEARER": 1,
  "NOW": 8,
  "HEADS": 2,
  "JERK": 1,
  "TOWARD": 23,
  "SOUND": 3,
  "TINTED": 3,
  "SHAKY": 1,
  "MOVING": 6,
  "CAMERA": 17,
  "TRUCK": 1,
  "THESE": 2,
  "SHOTS": 2,
  "ARE": 10,
  "STYLE": 1,
  "POV": 5,
  "WOLFEN": 1,
  "MAGNIFIED": 1,
  "GURGLING": 1,
  "HEAVY": 3,
  "BREATHING": 1,
  "WERECHICKEN": 46,
  "TERRIFIED": 2,
  "STARE": 6,
  "INTO": 50,
  "MOVES": 10,
  "CLOSER": 4,
  "HIS": 73,
  "SHADOW": 5,
  "FALLING": 1,
  "OVER": 18,
  "THEM": 13,
  "FLAP": 2,
  "THEIR": 14,
  "COOP": 3,
  "SQUAWKING": 3,
  "WILDLY": 2,
  "INT": 15,
  "LIVING": 3,
  "ROOM": 6,
  "MAUDE": 22,
  "ZEKE": 11,
  "SIT": 2,
  "SAGGING": 1,
  "COUCH": 3,
  "WATCHING": 3,
  "WEREWOLF": 2,
  "MOVIE": 2,
  "WHILE": 5,
  "MUNCHING": 1,
  "POPCORN": 5,
  "FROM": 29,
  "HUGE": 3,
  "BOWL": 11,
  "DISTRACTED": 1,
  "SUMP": 1,
  "STIRRIN": 1,
  "JES": 1,
  "SET": 2,
  "EASY": 3,
  "SHE": 10,
  "RISES": 7,
  "FOR": 15,
  "DOOR": 26,
  "TAKE": 6,
  "LOOK": 15,
  "SEE": 13,
  "CONTINUES": 7,
  "STARING": 3,
  "THROUGH": 31,
  "EYES": 19,
  "DISTANT": 3,
  "IMAGE": 1,
  "FLASHLIGHT": 4,
  "APPROACHING": 3,
  "PEN": 1,
  "OPENING": 2,
  "GATE": 2,
  "STARTS": 8,
  "ENTERS": 4,
  "LEAVING": 2,
  "OPEN": 17,
  "COMPOUND": 1,
  "EMPTY": 6,
  "CROSSES": 1,
  "WOODEN": 1,
  "GOES": 8,
  "HERE": 10,
  "CHICK": 4,
  "OTS": 1,
  "OUT": 40,
  "HER": 11,
  "BEAM": 2,
  "ILLUMINATES": 1,
  "COWERING": 1,
  "ROOSTS": 1,
  "CORNER": 2,
  "CLUCK": 5,
  "NERVOUSLY": 1,
  "WHAT": 18,
  "GOT": 3,
  "YOU": 22,
  "GIRLS": 1,
  "DURNED": 1,
  "UPSET": 1,
  "THERE": 16,
  "COYOTE": 1,
  "SNEAKIN": 1,
  "ROUND": 1,
  "SUDDENLY": 12,
  "BACK": 15,
  "WALL": 4,
  "LOW": 4,
  "GUTTERAL": 1,
  "CLU": 5,
  "UCK": 1,
  "LOOKS": 19,
  "SHOULDER": 4,
  "REACTS": 3,
  "EYED": 3,
  "GROTESQUE": 1,
  "THREE": 10,
  "TIMES": 1,
  "SIZE": 3,
  "ORDINARY": 1,
  "ROOSTER": 2,
  "FRAMED": 1,
  "MOONLIT": 1,
  "DOORWAY": 3,
  "OPENS": 5,
  "ITS": 17,
  "FANGED": 3,
  "BEAK": 5,
  "HORRIFYING": 1,
  "SHRIEK": 3,
  "SPRINGS": 2,
  "WINGS": 8,
  "FLAPPING": 2,
  "FRIGHTENING": 2,
  "CLOSE": 6,
  "OLD": 3,
  "BLACK": 1,
  "WHITE": 3,
  "MELODRAMATIC": 1,
  "MUSIC": 4,
  "MAN": 5,
  "TURNS": 6,
  "CONTINUATION": 1,
  "PREVIOUS": 1,
  "EATING": 3,
  "WALKS": 2,
  "STIFFLY": 1,
  "BEHIND": 17,
  "HIM": 21,
  "BLANKLY": 1,
  "WITHOUT": 1,
  "LOOKING": 17,
  "EVERYTHIN": 1,
  "OKAY": 3,
  "STARES": 3,
  "GLASSY": 1,
  "CLUCKS": 6,
  "QUIETLY": 1,
  "SAY": 1,
  "PAN": 6,
  "DOWN": 20,
  "BELOW": 2,
  "WAIST": 3,
  "REVEAL": 4,
  "THAT": 27,
  "TURNING": 4,
  "FEET": 16,
  "FIRST": 5,
  "SHOES": 1,
  "RIP": 2,
  "APART": 2,
  "LARGE": 4,
  "YELLOW": 2,
  "SPROUT": 1,
  "DRESS": 1,
  "SWELLS": 1,
  "SPLITS": 1,
  "REVEALING": 5,
  "FEATHERED": 2,
  "BODY": 8,
  "UNDERNEATH": 2,
  "ONLY": 5,
  "PIECE": 3,
  "CLOTHING": 1,
  "LEFT": 3,
  "APRON": 3,
  "ONE": 18,
  "FOOT": 7,
  "SCRATCHES": 1,
  "FLOOR": 3,
  "MORE": 4,
  "WIDER": 2,
  "ANGLE": 9,
  "FULLSHOT": 1,
  "COMPLETELY": 2,
  "TRANSFORMED": 1,
  "SIX": 8,
  "TALL": 11,
  "LEAPS": 3,
  "PERCH": 1,
  "THRUSTING": 1,
  "HEAD": 11,
  "REPEATEDLY": 1,
  "LAP": 1,
  "PECKING": 5,
  "CLEAN": 1,
  "JAW": 1,
  "HANGS": 2,
  "SPEECHLESS": 1,
  "DROOLING": 2,
  "RIGHT": 17,
  "SCRAMBLES": 2,
  "BACKWARDS": 2,
  "OFF": 21,
  "SCENE": 1,
  "HEAR": 5,
  "LOUD": 6,
  "WITHIN": 3,
  "HOUSE": 1,
  "FEATHERS": 6,
  "FLY": 4,
  "WINDOWS": 1,
  "GET": 8,
  "AWAY": 6,
  "SCAT": 1,
  "SHOO": 1,
  "SLIGHT": 1,
  "HILLTOP": 1,
  "SEEMS": 1,
  "BEND": 1,
  "INSIDIOUS": 1,
  "GRIN": 1,
  "DISTANCE": 5,
  "HELP": 2,
  "ELP": 1,
  "ESTABLISHING": 2,
  "GHOSTBUSTERS": 14,
  "EGON": 68,
  "COULD": 2,
  "HOLD": 2,
  "WEATHER": 18,
  "BALLOON": 17,
  "BIT": 2,
  "MINUTE": 3,
  "LABORATORY": 1,
  "PETER": 59,
  "RAY": 74,
  "STAND": 2,
  "HOLDING": 4,
  "BIG": 16,
  "PLASTIC": 1,
  "BAGS": 7,
  "TRASH": 8,
  "OBVIOUSLY": 2,
  "ANNOYED": 1,
  "ARMFUL": 1,
  "PILED": 1,
  "HIGH": 4,
  "CAN": 9,
  "SLIMER": 66,
  "HOVERS": 6,
  "STICKING": 1,
  "NOSE": 4,
  "LIKE": 18,
  "DOG": 2,
  "FINALLY": 3,
  "DIVES": 2,
  "YOUR": 4,
  "WINSTON": 53,
  "KITCHEN": 6,
  "DOING": 4,
  "DISHES": 1,
  "BUSY": 2,
  "TESTING": 1,
  "PINK": 1,
  "BUBBLE": 3,
  "HALF": 4,
  "LEVER": 3,
  "REMOTE": 2,
  "CONTROL": 6,
  "UNIT": 1,
  "PREOCCUPIED": 2,
  "ABOVE": 13,
  "CHECKS": 2,
  "WATCH": 2,
  "FIFTY": 1,
  "SECONDS": 1,
  "EXCHANGE": 3,
  "PAINED": 1,
  "GLANCES": 2,
  "AWKWARDLY": 1,
  "ATTEMPTS": 1,
  "PICK": 1,
  "BAG": 2,
  "STUMBLES": 2,
  "VISION": 1,
  "BLOCKED": 1,
  "MOVE": 3,
  "WHEN": 3,
  "LOWERS": 1,
  "FRAME": 1,
  "BOUNCE": 2,
  "WHICH": 3,
  "SENDS": 1,
  "FLYING": 3,
  "LIB": 1,
  "REACTIONS": 1,
  "LANDS": 2,
  "BUTT": 2,
  "SQUEALS": 4,
  "MUFFLED": 1,
  "SQUEAL": 2,
  "COMES": 3,
  "SHOOTING": 3,
  "LOWER": 1,
  "FLAT": 1,
  "FRISBEE": 1,
  "SHAKES": 2,
  "HIMSELF": 1,
  "SPRAYING": 1,
  "SLIME": 2,
  "ALL": 7,
  "PISSED": 1,
  "SARCASTIC": 3,
  "THANKS": 2,
  "REALLY": 3,
  "NEEDED": 1,
  "SORREEE": 1,
  "HELPS": 2,
  "TELEPHONE": 2,
  "RINGS": 2,
  "IRRITATED": 2,
  "PHONE": 3,
  "RINGING": 1,
  "BESIDE": 5,
  "WORKBENCH": 2,
  "CONTROLS": 3,
  "SLEEVES": 1,
  "ROLLED": 1,
  "WIPING": 1,
  "PLATE": 2,
  "DISH": 1,
  "TOWEL": 1,
  "WEARING": 6,
  "NEVERMIND": 2,
  "WOULDN": 2,
  "WANT": 2,
  "STRAIN": 1,
  "YOURSELF": 1,
  "PICKS": 3,
  "CENTRAL": 1,
  "EXCITED": 3,
  "CHATTER": 1,
  "CALM": 1,
  "WHERE": 4,
  "BEAT": 7,
  "LISTENS": 1,
  "AGAIN": 6,
  "HAVE": 9,
  "ARMS": 4,
  "EVEN": 3,
  "DRAGGING": 1,
  "READY": 3,
  "THIS": 16,
  "SOME": 9,
  "FARMER": 1,
  "SAYS": 1,
  "WIFE": 3,
  "WAS": 7,
  "EATEN": 1,
  "GIANT": 6,
  "HEY": 2,
  "BAKED": 1,
  "FALSE": 1,
  "ALARM": 1,
  "SOUNDS": 2,
  "BETTER": 2,
  "THAN": 2,
  "CHORES": 2,
  "DROPS": 3,
  "LET": 6,
  "ROLL": 1,
  "ALSO": 1,
  "ABANDON": 1,
  "EXIT": 2,
  "STILL": 11,
  "OBLIVIOUS": 1,
  "WORKS": 2,
  "THINK": 3,
  "PERFECTED": 1,
  "GUYS": 8,
  "COUNTRY": 2,
  "ROAD": 1,
  "ECTO": 16,
  "ROARS": 2,
  "SIREN": 2,
  "LIGHTS": 5,
  "GOING": 2,
  "MINUS": 1,
  "GEAR": 1,
  "SEAT": 2,
  "SURE": 3,
  "FEELS": 1,
  "STRANGE": 2,
  "NOT": 12,
  "HAVING": 1,
  "WHY": 2,
  "LATELY": 1,
  "DRIVING": 2,
  "BUT": 14,
  "SOMETHIN": 1,
  "SELLS": 1,
  "IDEA": 2,
  "RICH": 1,
  "FOLDED": 1,
  "GRUMPILY": 1,
  "GOOD": 6,
  "HIRE": 1,
  "MAID": 1,
  "SHARE": 1,
  "SPEEDS": 2,
  "MOONLIGHT": 3,
  "NESTING": 1,
  "HAYSTACK": 5,
  "SHAKE": 5,
  "RUFFLES": 1,
  "EGG": 30,
  "LAYING": 1,
  "SITS": 4,
  "ENORMOUS": 2,
  "BENEATH": 1,
  "SQUAWKS": 4,
  "STRUTS": 2,
  "CORNFIELD": 1,
  "EARS": 1,
  "CORN": 1,
  "LISTEN": 1,
  "SERIOUSLY": 1,
  "SPEAKS": 1,
  "BUYING": 1,
  "HAD": 3,
  "DID": 5,
  "BIGGEST": 2,
  "DANG": 1,
  "EVER": 2,
  "SEEN": 5,
  "MEBBE": 1,
  "ROLLS": 2,
  "SHOULDN": 1,
  "HARD": 1,
  "FIND": 3,
  "JOTTING": 1,
  "INFO": 1,
  "NOTEPAD": 1,
  "ANY": 2,
  "DISTINGUISHING": 1,
  "MARKS": 1,
  "GRABS": 3,
  "ARM": 3,
  "USHERING": 1,
  "FRONT": 8,
  "THANK": 1,
  "SIR": 1,
  "PUT": 2,
  "MISSING": 3,
  "REPORT": 1,
  "PARKED": 1,
  "BEEN": 2,
  "WATCHIN": 1,
  "TOO": 5,
  "MANY": 1,
  "HORROR": 1,
  "MOVIES": 1,
  "MUCH": 1,
  "GREASY": 1,
  "DEALING": 1,
  "BONAFIDE": 1,
  "STOP": 6,
  "DISBELIEF": 3,
  "SERIOUS": 1,
  "EXPLAIN": 2,
  "THOSE": 2,
  "POINTS": 2,
  "STANDING": 4,
  "BOTH": 2,
  "TWO": 3,
  "FOOTPRINTS": 1,
  "FOLLOW": 1,
  "TRACKS": 2,
  "POWERFUL": 1,
  "FLASHLIGHTS": 4,
  "ACROSS": 2,
  "FIELD": 1,
  "SPOTTED": 1,
  "HAYSTACKS": 1,
  "AHEAD": 1,
  "BLOODHOUND": 1,
  "SNIFFS": 1,
  "FLOATS": 3,
  "ALONG": 4,
  "ILLUMINATED": 1,
  "LEAD": 1,
  "BONK": 1,
  "BACKS": 1,
  "SHOT": 10,
  "RUBBING": 2,
  "POP": 3,
  "WIDE": 8,
  "AMAZED": 1,
  "GASP": 1,
  "ENTER": 2,
  "PLAY": 1,
  "SITTING": 1,
  "ATOP": 1,
  "TELL": 2,
  "GIMME": 1,
  "HAND": 8,
  "EASE": 1,
  "HOLDS": 4,
  "PKE": 4,
  "METER": 6,
  "NOTHING": 1,
  "REGISTERS": 1,
  "HOW": 11,
  "COME": 5,
  "READING": 4,
  "DUNNO": 2,
  "HEADQUARTERS": 1,
  "RUN": 7,
  "TESTS": 1,
  "MAYBE": 3,
  "ANSWERS": 1,
  "LEAVIN": 1,
  "LAID": 2,
  "HAS": 3,
  "GOTTA": 4,
  "SOMEPLACE": 1,
  "GONNA": 4,
  "THROWS": 1,
  "HANDS": 7,
  "SIGH": 2,
  "MON": 2,
  "START": 3,
  "SHAKING": 3,
  "WERECHICKENS": 4,
  "CARRYING": 2,
  "OTHER": 5,
  "DIRECTION": 1,
  "LAB": 7,
  "CARRY": 1,
  "REAL": 1,
  "WORK": 2,
  "ABOUT": 7,
  "ANALYZING": 1,
  "INTERESTING": 1,
  "SECOND": 1,
  "DESK": 2,
  "DON": 7,
  "WANNA": 2,
  "LONG": 6,
  "FRAGRANT": 1,
  "BARNYARD": 1,
  "TAKING": 1,
  "SHOWER": 2,
  "HITTING": 1,
  "SHEETS": 1,
  "EXITS": 2,
  "ZIPS": 2,
  "ELBOWS": 1,
  "CHIN": 1,
  "EYEING": 1,
  "EXPECTANTLY": 1,
  "PUSHES": 2,
  "GLASSES": 3,
  "TIP": 1,
  "BLINKS": 1,
  "SKY": 2,
  "PANS": 1,
  "TINY": 1,
  "FIGURES": 1,
  "BARN": 6,
  "SHINING": 1,
  "CLOSED": 2,
  "MAIN": 2,
  "TIRED": 1,
  "GETTIN": 1,
  "PRETTY": 1,
  "LATE": 2,
  "ISN": 1,
  "SHH": 1,
  "EXTENDS": 1,
  "BEEPS": 1,
  "INCESSANTLY": 1,
  "VOICE": 1,
  "UNCLIPPING": 1,
  "BLASTER": 3,
  "SLOWLY": 2,
  "CREAK": 1,
  "PEERING": 1,
  "CAUTIOUSLY": 3,
  "BEEPING": 2,
  "BEFORE": 6,
  "DARK": 2,
  "EXCEPT": 3,
  "SLANTING": 1,
  "LOFT": 1,
  "WINDOW": 7,
  "BEAMS": 2,
  "WOOD": 1,
  "CREAKS": 1,
  "HAY": 1,
  "RUSTLES": 1,
  "JUNKY": 1,
  "MACHINERY": 1,
  "PLACE": 3,
  "CREEPY": 1,
  "FEEL": 3,
  "SLAMS": 2,
  "SHUT": 5,
  "BEATING": 1,
  "SCURRIES": 1,
  "DARKNESS": 1,
  "JUMPS": 3,
  "SHINES": 1,
  "LOFTS": 1,
  "CATCHES": 2,
  "COUPLE": 1,
  "STARTLED": 5,
  "PIGEONS": 1,
  "PINION": 1,
  "WHISTLING": 1,
  "REACTION": 1,
  "RELIEVED": 1,
  "SIGHS": 1,
  "WHISPER": 1,
  "SOMETHING": 2,
  "VERY": 2,
  "CLOSING": 1,
  "WHEEL": 2,
  "FACE": 5,
  "MENACINGLY": 1,
  "SLIGHTLY": 1,
  "HOPS": 1,
  "FORWARD": 3,
  "STREAK": 1,
  "HANG": 3,
  "SIDES": 2,
  "EVIL": 1,
  "BACKING": 2,
  "BLASTERS": 3,
  "LEVELED": 2,
  "UGLY": 1,
  "POSTURES": 1,
  "ANGRILY": 1,
  "BAD": 3,
  "CHOICE": 1,
  "WORDS": 1,
  "SHRIEKING": 1,
  "SQUAWK": 1,
  "ZOOM": 1,
  "FIRE": 2,
  "PROTON": 7,
  "STREAMS": 5,
  "CATCH": 1,
  "MID": 3,
  "AIR": 4,
  "VAULTS": 1,
  "HALTING": 1,
  "LEAP": 3,
  "SUSPENDING": 1,
  "CORONA": 1,
  "ENERGY": 1,
  "HIDEOUS": 2,
  "SPIRIT": 11,
  "WRITHING": 2,
  "SHAPELESS": 1,
  "MONSTROUS": 3,
  "GLOWING": 1,
  "FANGS": 3,
  "LETS": 2,
  "ROAR": 2,
  "FIRING": 2,
  "GUN": 2,
  "SNAPS": 5,
  "TRAP": 12,
  "LOOSE": 1,
  "BELT": 1,
  "TOSSES": 2,
  "ONTO": 3,
  "POPS": 4,
  "STRUGGLING": 2,
  "CAUGHT": 2,
  "GUIDE": 5,
  "ALMOST": 2,
  "SUCKED": 2,
  "NORMAL": 5,
  "SINGED": 1,
  "WELL": 4,
  "TAKES": 3,
  "CARE": 1,
  "SMOKING": 1,
  "FOOTER": 1,
  "ATE": 2,
  "STOPS": 7,
  "JUST": 4,
  "THOUGHT": 1,
  "PAUSES": 1,
  "CARRIES": 1,
  "HELPING": 1,
  "STRAINING": 2,
  "TIME": 2,
  "EXAMINE": 1,
  "TONIGHT": 2,
  "PREPARE": 1,
  "DEMONSTRATION": 1,
  "TOMORROW": 1,
  "MORNING": 4,
  "ELBOW": 1,
  "REFRIGERATOR": 1,
  "INSIDE": 4,
  "SAFE": 1,
  "YEAH": 3,
  "CLOSES": 2,
  "FRIDGE": 2,
  "YAWN": 1,
  "GOODNIGHT": 1,
  "SNORING": 1,
  "HOVERING": 2,
  "BED": 2,
  "DREAM": 3,
  "VARIOUS": 2,
  "KINDS": 1,
  "FOOD": 1,
  "DANCING": 1,
  "SINGING": 1,
  "BARS": 1,
  "LOS": 1,
  "LOBOS": 1,
  "BAMBA": 1,
  "CALIFORNIA": 1,
  "RAISINS": 1,
  "GRAPEVINE": 1,
  "ASLEEP": 1,
  "LICKS": 1,
  "LIPS": 3,
  "HUNGRILY": 1,
  "MOUTH": 4,
  "INCREDIBLY": 1,
  "POUNCES": 1,
  "ENTIRE": 1,
  "TEETH": 1,
  "JARRING": 2,
  "CHOMP": 1,
  "EXPLODES": 2,
  "WAKING": 1,
  "HUNGRY": 1,
  "TUMMY": 1,
  "FOOOOOOD": 1,
  "SKIDS": 2,
  "WHIPS": 1,
  "SEES": 2,
  "LICKING": 1,
  "YUMMY": 1,
  "EDGE": 1,
  "SHELF": 1,
  "WEIGHT": 1,
  "DRIVES": 1,
  "STRAIGHT": 2,
  "BOUNCES": 1,
  "STOMACH": 1,
  "TWICE": 1,
  "GETS": 4,
  "GRIP": 1,
  "LITTLE": 2,
  "GREEN": 2,
  "BRAINS": 1,
  "GRUNTS": 1,
  "SHOVES": 1,
  "OVEN": 4,
  "HEAT": 1,
  "INTERIOR": 1,
  "GLOWS": 1,
  "QUIVER": 2,
  "HUMS": 2,
  "BUSILY": 1,
  "SETS": 2,
  "TABLE": 4,
  "PLACEMAT": 1,
  "UTENSILS": 1,
  "SALT": 1,
  "PEPPER": 1,
  "KETCHUP": 1,
  "MUSTARD": 1,
  "MAYO": 1,
  "RELISH": 1,
  "FLURRY": 1,
  "ACTIVITY": 1,
  "FOCUSES": 1,
  "PERSONAL": 1,
  "SPOT": 1,
  "HUMMING": 2,
  "BEGIN": 1,
  "CRACK": 1,
  "PREPARING": 1,
  "FEAST": 1,
  "PUTS": 3,
  "BIB": 2,
  "UNAWARE": 1,
  "BANG": 1,
  "PRACTICALLY": 1,
  "FLIES": 5,
  "BABY": 1,
  "SNARLING": 3,
  "CACKLING": 2,
  "BUG": 1,
  "PAW": 1,
  "SCREAM": 4,
  "BARRELS": 1,
  "SINK": 1,
  "FAUCET": 1,
  "STUCK": 1,
  "SHAMPOOING": 1,
  "HAIR": 1,
  "NOZZLE": 1,
  "HUGS": 1,
  "TIGHTLY": 1,
  "NECK": 5,
  "SCARING": 1,
  "HELL": 3,
  "YELL": 1,
  "BOUT": 1,
  "PRIVACY": 1,
  "POINTING": 3,
  "MONSTER": 3,
  "INNA": 1,
  "NODS": 3,
  "HUH": 2,
  "IMITATES": 1,
  "FAMILIAR": 1,
  "APPEARS": 2,
  "GROWS": 1,
  "REAR": 3,
  "VIEW": 4,
  "CREEPS": 1,
  "BITES": 2,
  "PULLS": 3,
  "CLAWS": 1,
  "CLATTERING": 1,
  "FADING": 1,
  "DAZED": 2,
  "TOES": 2,
  "LEATHER": 1,
  "TRANSFORMATION": 3,
  "COVERALLS": 2,
  "LEGS": 4,
  "MIDRIFF": 1,
  "TURN": 7,
  "SPROUTS": 1,
  "HALL": 1,
  "DRESSED": 1,
  "BACKPACK": 1,
  "RUNS": 2,
  "FLINGS": 1,
  "SEEING": 1,
  "WHO": 5,
  "ANYTHING": 1,
  "FREAKS": 1,
  "ROCKETS": 1,
  "NEAREST": 1,
  "HOLY": 1,
  "COW": 1,
  "RAISES": 1,
  "FLAPS": 1,
  "BULGING": 1,
  "GROWLS": 1,
  "IMPRESSIVE": 1,
  "BARED": 1,
  "ATTACK": 1,
  "MODE": 1,
  "STEPS": 2,
  "POWER": 2,
  "LIFE": 1,
  "HORRIFIED": 1,
  "BIRD": 2,
  "BRAIN": 1,
  "WAIT": 1,
  "FUST": 1,
  "THROWER": 1,
  "FIRES": 2,
  "SENDING": 1,
  "STREAM": 1,
  "CEILING": 1,
  "BARELY": 2,
  "SURPRISED": 1,
  "CORRIDOR": 1,
  "KICKS": 1,
  "QUICKLY": 1,
  "LOCKS": 1,
  "NEARBY": 1,
  "WORRIED": 2,
  "SHUDDERS": 1,
  "UNSEEN": 1,
  "TRIES": 1,
  "BREAK": 1,
  "WRONG": 1,
  "THING": 2,
  "HATCHED": 2,
  "BITTEN": 1,
  "STARTING": 3,
  "SPLINTER": 1,
  "BULGE": 1,
  "BATTERING": 2,
  "KIDDING": 1,
  "CERTAIN": 1,
  "RESEMBLANCE": 1,
  "HAPPENED": 3,
  "QUIET": 2,
  "SUDDEN": 1,
  "HURRIES": 1,
  "BEYOND": 2,
  "BEGINNING": 1,
  "DISAPPEAR": 1,
  "LUNAR": 1,
  "ECLIPSE": 3,
  "TEN": 3,
  "YEARS": 1,
  "BEING": 2,
  "OTHERS": 3,
  "APPEAR": 1,
  "DURING": 2,
  "NEXT": 1,
  "FEW": 1,
  "MINUTES": 3,
  "PECKS": 1,
  "TENTATIVE": 1,
  "CLOTHES": 1,
  "CONFUSED": 1,
  "TATTERED": 1,
  "SKIRT": 1,
  "NAKED": 1,
  "GIVES": 2,
  "SLOPPY": 1,
  "KISS": 1,
  "NEWS": 3,
  "TURNED": 1,
  "SLIP": 1,
  "END": 2,
  "WIDEN": 1,
  "HURRIEDLY": 2,
  "THUMBS": 1,
  "TOBIN": 4,
  "FLIPPING": 1,
  "BOOK": 1,
  "WERE": 4,
  "AARDVARKS": 1,
  "BEARS": 1,
  "READS": 2,
  "ANYONE": 3,
  "WILL": 2,
  "BROUGHT": 1,
  "RUBS": 1,
  "REMEMBER": 1,
  "BITE": 1,
  "CLEARLY": 1,
  "STAY": 1,
  "ACCORDING": 1,
  "ANTIDOTE": 1,
  "FAST": 2,
  "LASTS": 1,
  "CUPBOARD": 1,
  "GRABBING": 1,
  "BOTTLES": 1,
  "STUFF": 1,
  "ADDS": 1,
  "INGREDIENTS": 1,
  "MIXING": 2,
  "STIRS": 1,
  "TABLESPOON": 2,
  "PAPRIKA": 1,
  "CLOVE": 1,
  "GARLIC": 1,
  "PARSLEY": 1,
  "COLOR": 1,
  "CUP": 1,
  "GELATIN": 1,
  "ECLIPSED": 1,
  "EMERGE": 1,
  "PUPILS": 1,
  "CONSTRICTED": 1,
  "PERSPIRING": 1,
  "WEAKLY": 1,
  "SHOULDERS": 2,
  "FINE": 1,
  "SHOUTS": 1,
  "HURRY": 2,
  "CHICKENBANE": 4,
  "RUMMAGES": 1,
  "SHELVES": 1,
  "AGHAST": 1,
  "PANICKY": 3,
  "LIQUID": 1,
  "FOLLOWS": 1,
  "ONCE": 2,
  "POPPING": 1,
  "YELLS": 1,
  "CHANGING": 1,
  "RUSH": 1,
  "BREATHLESS": 2,
  "QUICK": 1,
  "DRINK": 1,
  "POTION": 2,
  "GULPS": 1,
  "SWALLOWING": 1,
  "GULPING": 1,
  "DRINKS": 1,
  "TRANSFORM": 1,
  "BREAKING": 1,
  "RISE": 3,
  "DRAMATIC": 1,
  "AFTER": 3,
  "INCLUDE": 1,
  "OWN": 1,
  "PARTLY": 1,
  "WORKED": 1,
  "BECAUSE": 1,
  "HAFTA": 1,
  "RUFFLED": 1,
  "LOGICAL": 1,
  "SOLUTION": 1,
  "EVERY": 1,
  "PROBLEM": 1,
  "STRANDS": 1,
  "NAPE": 1,
  "FRIGHTENED": 2,
  "CAT": 1,
  "TEST": 1,
  "TUBE": 1,
  "RACK": 1,
  "SOMEWHERE": 1,
  "MAKES": 3,
  "DRUMSTICKS": 1,
  "ELSE": 1,
  "OFFENSE": 1,
  "DASH": 1,
  "AERIAL": 1,
  "MANHATTAN": 2,
  "GLIDES": 1,
  "RUNNING": 2,
  "BLINKING": 2,
  "BINOCULARS": 2,
  "RADIO": 5,
  "MIKE": 2,
  "PEEP": 1,
  "DIRTY": 1,
  "PUN": 1,
  "INTENDED": 1,
  "SEVERAL": 1,
  "PEOPLE": 2,
  "SCREAMING": 2,
  "PASSES": 1,
  "EXITING": 1,
  "CRANKS": 1,
  "SCREECHING": 1,
  "DOORS": 2,
  "STORE": 1,
  "ENTRANCE": 1,
  "PANICKED": 1,
  "BOX": 4,
  "BOY": 1,
  "FIFTEEN": 2,
  "OUTTA": 1,
  "SPLIT": 1,
  "OPPOSITE": 1,
  "DIRECTIONS": 1,
  "FLANKING": 1,
  "AISLES": 2,
  "AISLE": 3,
  "FAR": 2,
  "SAME": 1,
  "MARKET": 1,
  "THRASHED": 1,
  "SPILLED": 1,
  "GROCERIES": 1,
  "EVERYWHERE": 1,
  "REACH": 1,
  "JOINS": 1,
  "LOSE": 1,
  "DIDN": 1,
  "MEAT": 1,
  "DEPT": 1,
  "BUTCHER": 4,
  "HIDING": 1,
  "UNDER": 1,
  "BLOCK": 1,
  "TREMBLING": 2,
  "CAME": 2,
  "THIRTY": 2,
  "PARKING": 1,
  "LOT": 1,
  "TRAIL": 1,
  "CRUSHED": 1,
  "CARS": 3,
  "MIDDLE": 1,
  "RACE": 1,
  "INDUSTRIAL": 1,
  "DISTRICT": 1,
  "CHOPPER": 3,
  "SKIMS": 1,
  "PAST": 1,
  "FOUR": 1,
  "STORY": 2,
  "BUILDINGS": 3,
  "ADMIT": 1,
  "DEFINITELY": 1,
  "BUY": 1,
  "GROWING": 1,
  "COVERS": 1,
  "LAUGHTER": 1,
  "FIZZING": 1,
  "ABSURD": 1,
  "REARS": 1,
  "DEAFENING": 2,
  "BUFFETED": 2,
  "JAMS": 1,
  "STICK": 2,
  "STEEP": 1,
  "BANKING": 1,
  "DIVE": 1,
  "ESCAPING": 1,
  "THIN": 1,
  "RETREATING": 1,
  "TAIL": 2,
  "SHAKEN": 1,
  "JELL": 1,
  "WALKING": 1,
  "OUR": 1,
  "WAY": 1,
  "FLOORS": 1,
  "ACCELERATE": 1,
  "BUNKROOM": 1,
  "PERCHED": 1,
  "SILL": 2,
  "PENSIVELY": 1,
  "FLUTTERS": 1,
  "GRAVITY": 1,
  "JANINE": 3,
  "FROZEN": 1,
  "CHEEKS": 1,
  "COAT": 3,
  "PLEASE": 1,
  "DUE": 1,
  "BOARD": 5,
  "FORTY": 1,
  "FIVE": 2,
  "TOTALLY": 1,
  "BEWILDERED": 1,
  "THINKS": 1,
  "ASKING": 1,
  "RAINCOAT": 3,
  "HOOK": 1,
  "COVERED": 1,
  "MEETING": 1,
  "TRUST": 1,
  "MIND": 1,
  "LEAST": 1,
  "PROTRUDING": 1,
  "SLIT": 1,
  "TOWN": 1,
  "STEPPING": 1,
  "KICKING": 1,
  "POLES": 2,
  "ETC": 1,
  "GODZILLA": 1,
  "STREETS": 2,
  "PEDESTRIANS": 1,
  "FLEE": 1,
  "WALLA": 3,
  "FOLLOWING": 1,
  "HEADING": 1,
  "EMPIRE": 9,
  "STATE": 9,
  "BUILDING": 9,
  "BLARING": 1,
  "CHECK": 1,
  "BLDG": 1,
  "DAWN": 1,
  "SUN": 2,
  "APPROACHES": 1,
  "EACH": 5,
  "SCREECHES": 1,
  "HALT": 1,
  "ANGLING": 1,
  "UPWARD": 1,
  "CONCRETE": 1,
  "CANYON": 1,
  "FLATTENING": 1,
  "STREET": 4,
  "LAMPS": 1,
  "ROGER": 1,
  "LEANS": 1,
  "SIDE": 3,
  "DOWNWARD": 1,
  "CROSSING": 1,
  "FLAILS": 1,
  "KNOCKING": 1,
  "BASHING": 1,
  "EMERGES": 2,
  "FILLS": 1,
  "SCREEN": 1,
  "TRANSPARENT": 1,
  "FILM": 1,
  "ENRAGED": 1,
  "REEL": 1,
  "DRAW": 1,
  "ANGRY": 2,
  "BOOT": 1,
  "STOMPS": 1,
  "TRIGGER": 1,
  "CONTACT": 1,
  "SMALL": 2,
  "STORM": 2,
  "ERUPTS": 1,
  "SPARKS": 1,
  "LIGHTNING": 1,
  "BOLTS": 1,
  "HURRICANE": 1,
  "BLOWS": 1,
  "THROWERS": 1,
  "CONTINUE": 1,
  "SHOUT": 1,
  "NOISE": 1,
  "SOMEBODY": 1,
  "FORGOT": 1,
  "BOUNCING": 1,
  "WHOSE": 1,
  "JOB": 1,
  "LIGHT": 1,
  "FLASHES": 1,
  "RAPIDLY": 1,
  "BEGINS": 4,
  "GLOW": 1,
  "BLOW": 1,
  "WALKIE": 1,
  "TALKIE": 1,
  "OUTA": 1,
  "BANKS": 2,
  "GUNS": 1,
  "KNOCKED": 1,
  "RELEASED": 1,
  "FORCE": 1,
  "FREED": 1,
  "WHOOSHES": 1,
  "SKYWARD": 3,
  "ABRUPTLY": 1,
  "DISAPPEARS": 1,
  "CONTORTS": 1,
  "ANGER": 1,
  "HALFWAY": 1,
  "TOP": 3,
  "PULL": 1,
  "ICE": 2,
  "FINGER": 1,
  "FREEZES": 2,
  "TEMPERATURES": 1,
  "FREEZE": 3,
  "AUGUST": 1,
  "ROOFTOP": 2,
  "GROUP": 1,
  "SEATED": 2,
  "MEN": 1,
  "WOMEN": 1,
  "RAIN": 2,
  "DISTINGUISHED": 1,
  "MEMBERS": 3,
  "CAPABILITY": 1,
  "VISIBLE": 1,
  "DEVICE": 1,
  "WINGED": 1,
  "ENTERING": 1,
  "UPPER": 2,
  "ATMOSPHERE": 1,
  "CLOUD": 1,
  "FORMATIONS": 1,
  "OCCUR": 1,
  "PUZZLED": 2,
  "MUTTERING": 1,
  "ELECTRONICALLY": 1,
  "ALTER": 1,
  "CUT": 3,
  "CON": 1,
  "DITIONS": 1,
  "PRODUCE": 1,
  "SNOW": 5,
  "ASCENDS": 1,
  "ROTORS": 1,
  "BLOWING": 1,
  "EXPOSING": 1,
  "MOUTHS": 1,
  "DROP": 1,
  "AUDIENCE": 1,
  "FORCED": 1,
  "SMILE": 1,
  "WHISPERS": 1,
  "EAR": 1,
  "CLIMBS": 2,
  "SCALING": 1,
  "STORIES": 1,
  "ROPE": 1,
  "LADDER": 1,
  "HANGING": 1,
  "SETTLES": 1,
  "PASSENGER": 1,
  "ENGINE": 1,
  "BALLOONS": 1,
  "YES": 1,
  "CAKE": 1,
  "REACHES": 1,
  "SPIRE": 2,
  "COMFORTABLE": 1,
  "FLUFFING": 1,
  "EARLIER": 1,
  "CROW": 1,
  "LAY": 1,
  "DREAD": 1,
  "BUREAU": 1,
  "DRIFTS": 1,
  "HORIZONTALLY": 1,
  "DARKENS": 1,
  "CLOUDS": 2,
  "OPERATES": 1,
  "POSITION": 1,
  "EXTREME": 1,
  "SURROUNDING": 1,
  "FORMING": 1,
  "FALL": 2,
  "STICKS": 1,
  "TONGUE": 1,
  "SNOWFLAKES": 1,
  "BLIZZARD": 1,
  "PELTS": 1,
  "STIFFEN": 1,
  "FROST": 1,
  "FALLS": 1,
  "GAZE": 1,
  "CALLS": 1,
  "DESSERT": 1,
  "STEAMING": 1,
  "SOUP": 4,
  "BOWLS": 1,
  "EVERYONE": 2,
  "DINERS": 1,
  "POINT": 1,
  "WEARINESS": 1,
  "RAISING": 1,
  "BET": 1,
  "LEMME": 1,
  "GUESS": 1,
  "SPOONING": 1,
  "EAGERLY": 1,
  "ACTUALLY": 1,
  "PROBLEMS": 1,
  "BURST": 1,
  "CHAIRS": 1,
  "ADVANCE": 1,
  "PEER": 1,
  "SWISH": 1,
  "MAKING": 1,
  "MOTION": 1,
  "WALKMAN": 1,
  "RHYTHM": 1,
  "GROOVIN": 1,
  "JAMES": 3,
  "BROWN": 3,
  "TAPE": 1,
  "GROOVE": 1,
  "KNEW": 1,
  "WOULD": 1,
  "DISGUST": 1,
  "SUFFERING": 1,
  "OUTFIT": 1
};
export const COMMON_TOP20 = [
  [
    "RAY",
    74
  ],
  [
    "EGON",
    68
  ],
  [
    "SLIMER",
    66
  ],
  [
    "PETER",
    59
  ],
  [
    "WINSTON",
    53
  ],
  [
    "INTO",
    50
  ],
  [
    "CHICKEN",
    49
  ],
  [
    "WERECHICKEN",
    46
  ],
  [
    "OUT",
    40
  ],
  [
    "THROUGH",
    31
  ],
  [
    "EGG",
    30
  ],
  [
    "DOOR",
    26
  ],
  [
    "THEN",
    25
  ],
  [
    "TOWARD",
    23
  ],
  [
    "MAUDE",
    22
  ],
  [
    "HIM",
    21
  ],
  [
    "OFF",
    21
  ],
  [
    "DOWN",
    20
  ],
  [
    "EYES",
    19
  ],
  [
    "LOOKS",
    19
  ]
];
export const UNCOMMON_TOP20 = [
  [
    "ACROSS",
    2
  ],
  [
    "AISLES",
    2
  ],
  [
    "ALMOST",
    2
  ],
  [
    "ANGRY",
    2
  ],
  [
    "ANY",
    2
  ],
  [
    "APART",
    2
  ],
  [
    "APPEARS",
    2
  ],
  [
    "ATE",
    2
  ],
  [
    "BACKING",
    2
  ],
  [
    "BACKWARDS",
    2
  ],
  [
    "BAG",
    2
  ],
  [
    "BANKS",
    2
  ],
  [
    "BARELY",
    2
  ],
  [
    "BATTERING",
    2
  ],
  [
    "BEAM",
    2
  ],
  [
    "BEAMS",
    2
  ],
  [
    "BED",
    2
  ],
  [
    "BEEN",
    2
  ],
  [
    "BEEPING",
    2
  ],
  [
    "BEING",
    2
  ]
];

// Game-ready object
export const BOOK_FOR_GAME = {
  ...META,
  commonTop: COMMON_TOP20,
  uncommonTop: UNCOMMON_TOP20
};

export default BOOK_FOR_GAME;
